'use client';

import Link from 'next/link';
import Footer from '@/components/landing/Footer';
import Navigation from '@/components/landing/Navigation';

export default function PrivacyPolicyPage() {
  return (
    <div className="bg-white text-neutral-900 antialiased">
      <Navigation />

      <main className="pt-32 pb-20">
        <article className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <header className="mb-16">
            <h1 className="font-serif text-4xl sm:text-5xl text-neutral-900 mb-4">
              Privacy Policy
            </h1>
            <p className="text-neutral-500">Last updated: December 2025</p>
          </header>

          <div className="space-y-12">
            <section>
              <h2 className="font-serif text-2xl text-neutral-900 mb-6">Introduction</h2>
              <div className="space-y-4 text-neutral-600 leading-relaxed">
                <p>
                  Welcome to Lex AI Technologies Pvt. Ltd. (&quot;us&quot;, &quot;we&quot;, or
                  &quot;our&quot;). We operate lexailabs.com (the &quot;Service&quot;).
                </p>
                <p>
                  Our Privacy Policy governs your visit to lexailabs.com and explains how we
                  collect, safeguard, and disclose information resulting from your use of our
                  Service.
                </p>
                <p>
                  We use your data to provide and improve the Service. By using the Service, you
                  agree to the collection and use of information in accordance with this policy.
                  Unless otherwise defined in this Privacy Policy, the terms used here have the same
                  meanings as in our{' '}
                  <Link href="/terms" className="text-coral-600 hover:underline">
                    Terms and Conditions
                  </Link>
                  .
                </p>
              </div>
            </section>

            <section>
              <h2 className="font-serif text-2xl text-neutral-900 mb-6">Definitions</h2>
              <ul className="space-y-3 text-neutral-600 leading-relaxed list-disc pl-6">
                <li>
                  <strong className="text-neutral-900">Service:</strong> The lexailabs.com website
                  operated by Lex AI Technologies Pvt. Ltd.
                </li>
                <li>
                  <strong className="text-neutral-900">Personal Data:</strong> Data about a living
                  individual who can be identified from those data.
                </li>
                <li>
                  <strong className="text-neutral-900">Usage Data:</strong> Data collected
                  automatically, either generated by the use of the Service or from Service
                  infrastructure itself (e.g., duration of a page visit).
                </li>
                <li>
                  <strong className="text-neutral-900">Cookies:</strong> Small files stored on your
                  device (computer or mobile device).
                </li>
                <li>
                  <strong className="text-neutral-900">Data Controller:</strong> A person or entity
                  who determines the purposes and means of processing personal data. We are the Data
                  Controller of your data.
                </li>
                <li>
                  <strong className="text-neutral-900">
                    Data Processors (or Service Providers):
                  </strong>{' '}
                  Entities that process data on behalf of the Data Controller.
                </li>
                <li>
                  <strong className="text-neutral-900">Data Subject:</strong> Any living individual
                  who is the subject of Personal Data.
                </li>
                <li>
                  <strong className="text-neutral-900">The User:</strong> The individual using our
                  Service, corresponding to the Data Subject.
                </li>
              </ul>
            </section>

            <section>
              <h2 className="font-serif text-2xl text-neutral-900 mb-6">
                Information Collection and Use
              </h2>
              <div className="space-y-4 text-neutral-600 leading-relaxed">
                <p>
                  We collect different types of information for various purposes to provide and
                  improve our Service.
                </p>
              </div>

              <h3 className="font-serif text-xl text-neutral-900 mt-8 mb-4">Personal Data</h3>
              <div className="space-y-4 text-neutral-600 leading-relaxed">
                <p>
                  While using our Service, we may ask you to provide us with certain personally
                  identifiable information, which may include but is not limited to:
                </p>
                <ul className="space-y-2 list-disc pl-6">
                  <li>Email address</li>
                  <li>First name and last name</li>
                  <li>Phone number</li>
                  <li>Address (Country, State, Province, ZIP/Postal code, City)</li>
                  <li>Cookies and Usage Data</li>
                </ul>
                <p>
                  We may use your Personal Data to contact you with newsletters, marketing,
                  promotional materials, and other information. You can opt out by following the
                  unsubscribe link.
                </p>
              </div>

              <h3 className="font-serif text-xl text-neutral-900 mt-8 mb-4">Usage Data</h3>
              <div className="space-y-4 text-neutral-600 leading-relaxed">
                <p>
                  We may collect information that your browser sends whenever you visit our Service
                  or access it via a device.
                </p>
              </div>

              <h3 className="font-serif text-xl text-neutral-900 mt-8 mb-4">
                Tracking Cookies Data
              </h3>
              <div className="space-y-4 text-neutral-600 leading-relaxed">
                <p>
                  We use cookies and similar tracking technologies to track activity on our Service.
                  Examples of cookies we use:
                </p>
                <ul className="space-y-2 list-disc pl-6">
                  <li>
                    <strong className="text-neutral-900">Session Cookies:</strong> Used to operate
                    our Service.
                  </li>
                  <li>
                    <strong className="text-neutral-900">Preference Cookies:</strong> Used to
                    remember your preferences and settings.
                  </li>
                  <li>
                    <strong className="text-neutral-900">Security Cookies:</strong> Used for
                    security purposes.
                  </li>
                  <li>
                    <strong className="text-neutral-900">Advertising Cookies:</strong> Used to serve
                    relevant advertisements.
                  </li>
                </ul>
              </div>
            </section>

            <section>
              <h2 className="font-serif text-2xl text-neutral-900 mb-6">Use of Data</h2>
              <div className="space-y-4 text-neutral-600 leading-relaxed">
                <p>Lex AI Technologies Pvt. Ltd. uses collected data for various purposes:</p>
                <ul className="space-y-2 list-disc pl-6">
                  <li>To provide and maintain our Service</li>
                  <li>To notify you about changes to our Service</li>
                  <li>To allow participation in interactive features</li>
                  <li>To provide customer support</li>
                  <li>To monitor Service usage</li>
                  <li>To detect, prevent, and address technical issues</li>
                  <li>
                    To provide news, special offers, and general information (unless you opt out)
                  </li>
                  <li>For any other purposes with your consent</li>
                </ul>
              </div>
            </section>

            <section>
              <h2 className="font-serif text-2xl text-neutral-900 mb-6">Retention of Data</h2>
              <div className="space-y-4 text-neutral-600 leading-relaxed">
                <p>
                  We retain your Personal Data only as long as necessary for the purposes set out in
                  this Privacy Policy.
                </p>
              </div>
            </section>

            <section>
              <h2 className="font-serif text-2xl text-neutral-900 mb-6">Transfer of Data</h2>
              <div className="space-y-4 text-neutral-600 leading-relaxed">
                <p>
                  Your information, including Personal Data, may be transferred and maintained on
                  computers outside your state, province, country, or jurisdiction where data
                  protection laws may differ.
                </p>
              </div>
            </section>

            <section>
              <h2 className="font-serif text-2xl text-neutral-900 mb-6">Security of Data</h2>
              <div className="space-y-4 text-neutral-600 leading-relaxed">
                <p>
                  The security of your data is important to us, but no method of transmission over
                  the Internet or electronic storage is 100% secure.
                </p>
              </div>
            </section>

            <section>
              <h2 className="font-serif text-2xl text-neutral-900 mb-6">
                Your Data Protection Rights
              </h2>
              <ul className="space-y-3 text-neutral-600 leading-relaxed list-disc pl-6">
                <li>
                  <strong className="text-neutral-900">EU & EEA Residents:</strong> Your rights
                  under GDPR
                </li>
                <li>
                  <strong className="text-neutral-900">California Residents:</strong> Your rights
                  under CCPA
                </li>
              </ul>
            </section>

            <section>
              <h2 className="font-serif text-2xl text-neutral-900 mb-6">Service Providers</h2>
              <div className="space-y-4 text-neutral-600 leading-relaxed">
                <p>
                  We may employ third-party companies and individuals to facilitate our Service,
                  provide it on our behalf, or analyze its usage.
                </p>
              </div>
            </section>

            <section>
              <h2 className="font-serif text-2xl text-neutral-900 mb-6">Payments</h2>
              <div className="space-y-4 text-neutral-600 leading-relaxed">
                <p>
                  If we provide paid products or services, we use third-party payment processors. We
                  do not store or collect your payment card details.
                </p>
              </div>
            </section>

            <section>
              <h2 className="font-serif text-2xl text-neutral-900 mb-6">Children&apos;s Privacy</h2>
              <div className="space-y-4 text-neutral-600 leading-relaxed">
                <p>
                  Our Services are not intended for children under the age of 18. If we become aware
                  of collecting Personal Data from children without parental consent, we will take
                  steps to remove it.
                </p>
              </div>
            </section>

            <section>
              <h2 className="font-serif text-2xl text-neutral-900 mb-6">
                Changes to This Privacy Policy
              </h2>
              <div className="space-y-4 text-neutral-600 leading-relaxed">
                <p>
                  We may update our Privacy Policy from time to time. Any changes will be posted on
                  this page.
                </p>
              </div>
            </section>

            <section>
              <h2 className="font-serif text-2xl text-neutral-900 mb-6">Contact Us</h2>
              <div className="space-y-4 text-neutral-600 leading-relaxed">
                <p>
                  If you have any questions about this Privacy Policy, please contact us via email:
                </p>
                <p>
                  <a href="mailto:contact@lexailabs.com" className="text-coral-600 hover:underline">
                    contact@lexailabs.com
                  </a>
                </p>
              </div>
            </section>
          </div>
        </article>
      </main>

      <Footer />
    </div>
  );
}
